name=input("your name:")
mobile=int(input("mobile number:"))
account=int(input("account number:"))
ifsc=input("ifsc number:")
micr=input("micr number:")
email=input("e mail:")
dob=str(input("dob:"))
address=input("address:")

print(name)
print(mobile)
print(account)
print(ifsc)
print(micr)
print(email)
print(dob)
print(address)

print(name,"\n",mobile,"\n",account,"\n",ifsc,"\n",micr,"\n",email,"\n",dob,"\n",address)
